name: Attach DB
on: workflow_dispatch
jobs:
  attach:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Attach Postgres
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl postgres attach waw-trams-db -a waw-trams --yes
